.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/ISSUE_TEMPLATE/config.yml
- Bug report
- Feature request
- Discuss link
=> Add github issue templates

client/src/hooks/Dialog.tsx, client/src/http/Partition.ts, client/src/i18n/cn/button.ts, client/src/i18n/cn/dialog.ts, client/src/i18n/cn/success.ts, client/src/i18n/en/button.ts, client/src/i18n/en/dialog.ts, client/src/i18n/en/success.ts, client/src/pages/collections/Collections.tsx, client/src/pages/partitions/Types.ts, client/src/pages/partitions/partitions.tsx, client/src/styles/common.css
=> add load partition

client/src/http/Partition.ts, client/src/pages/collections/Create.tsx, client/src/pages/partitions/partitions.tsx
=> Add release partition

client/src/consts/Milvus.tsx, client/src/http/Index.ts, client/src/i18n/cn/common.ts, client/src/i18n/cn/dialog.ts, client/src/i18n/cn/index.ts, client/src/i18n/en/common.ts, client/src/i18n/en/dialog.ts, client/src/i18n/en/index.ts, client/src/pages/collections/CreateFields.tsx, client/src/pages/structure/Create.tsx, client/src/pages/structure/CreateForm.tsx, client/src/pages/structure/CreateStepTwo.tsx, client/src/pages/structure/IndexTypeElement.tsx, client/src/pages/structure/Structure.tsx, client/src/pages/structure/Types.ts, client/src/types/Common.ts, client/src/utils/Form.ts, client/src/utils/Validation.ts, server/src/schema/schema.service.ts
=> add create index

client/public/index.html, client/src/http/Index.ts, client/src/i18n/cn/index.ts, client/src/i18n/en/index.ts, client/src/pages/collections/Collection.tsx, client/src/pages/collections/Collections.tsx, client/src/pages/collections/Create.tsx, client/src/pages/connect/Connect.tsx, client/src/pages/overview/Overview.tsx, client/src/pages/overview/collectionCard/CollectionCard.tsx, client/src/pages/partitions/Create.tsx, client/src/pages/structure/CreateForm.tsx, client/src/pages/structure/IndexTypeElement.tsx, client/src/pages/structure/Structure.tsx, client/src/pages/structure/Types.ts, server/package.json, server/yarn.lock
=> add delete index

client/src/components/grid/Table.tsx, client/src/components/grid/Types.ts, client/src/components/grid/index.tsx, client/src/hooks/Pagination.ts, client/src/http/Collection.ts, client/src/pages/collections/Collections.tsx, client/src/pages/partitions/partitions.tsx, client/src/pages/structure/Structure.tsx, client/src/utils/__test__/Validation.spec.ts, server/src/collections/collections.service.ts
change page size to fit table height
=> Update table page size

client/src/components/customTabList/CustomTabList.tsx, client/src/components/grid/Table.tsx, client/src/components/layout/Layout.tsx, client/src/i18n/cn/common.ts, client/src/i18n/en/common.ts, client/src/pages/collections/CreateFields.tsx, client/src/pages/overview/collectionCard/CollectionCard.tsx, client/src/styles/common.css
=> fix style problem on Safari

client/src/components/grid/Table.tsx, client/src/components/status/StatusIcon.tsx, client/src/consts/Milvus.tsx, client/src/hooks/Pagination.ts, client/src/pages/connect/Connect.tsx, client/src/pages/structure/IndexTypeElement.tsx, client/src/pages/structure/Types.ts, server/src/collections/collections.service.ts
fix #77 
fix overview statistic card
=> fix pagination and update table style

client/src/components/cards/EmptyCard.tsx, client/src/components/customButton/CustomButton.tsx, client/src/components/customDialog/CustomDialog.tsx, client/src/components/customDialog/DeleteDialogTemplate.tsx, client/src/components/customInput/CustomInput.tsx, client/src/components/layout/Layout.tsx, client/src/components/menu/NavMenu.tsx, client/src/pages/collections/CreateFields.tsx, client/src/pages/collections/Types.ts, client/src/pages/connect/Connect.tsx, client/src/pages/partitions/partitions.tsx, client/src/pages/structure/Structure.tsx, client/src/styles/theme.ts
1. hide load / release partition
2. fix #70 
3. fix #76 
4. fix #73 
5. fix #75
=> hide load / release partition and update style

client/src/pages/structure/Structure.tsx
=> update index param font size

server/src/app.module.ts, server/src/auth/auth.service.ts, server/src/interceptors/index.ts, server/src/main.ts, server/src/middlewares/logger.ts, server/src/utils/ConsoleLogger.ts
=> add server logs

client/src/pages/collections/Collection.tsx
=> change collection tab order, structure as the first one

client/src/http/Collection.ts, client/src/http/Field.ts, client/src/i18n/cn/index.ts, client/src/i18n/en/index.ts, client/src/pages/schema/Schema.tsx, client/src/pages/schema/Types.ts
=> fix schema table missing description

client/src/hooks/Dialog.tsx, client/src/http/Collection.ts, client/src/pages/collections/CreateFields.tsx, client/src/pages/overview/Overview.tsx, client/src/pages/overview/collectionCard/CollectionCard.tsx, client/src/pages/overview/collectionCard/Types.ts
=> fix overview page release collection not working

client/src/components/grid/TableHead.tsx, client/src/components/grid/Types.ts, client/src/pages/collections/Collections.tsx, client/src/pages/schema/Schema.tsx
=> fix component table row sort not working

server/package.json, server/src/collections/collections.controller.ts, server/src/collections/collections.service.ts, server/src/collections/dto.ts, server/src/milvus/dto.ts, server/src/milvus/milvus.controller.ts, server/src/milvus/milvus.service.ts, server/src/utils/ConsoleLogger.ts, server/yarn.lock
=> add insert api

server/src/collections/collections.controller.ts, server/src/collections/collections.service.ts, server/src/collections/dto.ts
=> add search api

client/src/components/grid/ToolBar.tsx, client/src/components/grid/Types.ts, client/src/components/insert/Container.tsx, client/src/components/insert/Import.tsx, client/src/components/insert/Preview.tsx, client/src/components/insert/Status.tsx, client/src/components/insert/Types.ts, client/src/components/menu/SimpleMenu.tsx, client/src/components/uploader/Types.ts, client/src/components/uploader/Uploader.tsx, client/src/http/Collection.ts, client/src/http/Milvus.ts, client/src/pages/collections/Collections.tsx, client/src/pages/collections/Types.ts, client/src/pages/partitions/Partitions.tsx, client/src/pages/schema/Types.ts, client/src/utils/Insert.ts
=> update insert interactions

client/src/pages/connect/Connect.tsx, client/src/utils/Format.ts
=> Fix: Login: Should trim input of the address

client/src/components/advancedSearch/Dialog.tsx
- Expression element position fixed.
- Expression style.
=> fix: Refine advanced search

client/src/components/grid/Table.tsx, client/src/components/insert/Container.tsx, client/src/components/insert/Import.tsx, client/src/components/insert/Preview.tsx, client/src/components/insert/Types.ts, client/src/components/uploader/Types.ts, client/src/components/uploader/Uploader.tsx, client/src/consts/Insert.ts, client/src/consts/Milvus.tsx, client/src/http/Field.ts, client/src/i18n/cn/insert.ts, client/src/i18n/cn/search.ts, client/src/i18n/en/insert.ts, client/src/i18n/en/search.ts, client/src/pages/schema/Types.ts, client/src/pages/seach/SearchParams.tsx, client/src/pages/seach/Styles.ts, client/src/pages/seach/VectorSearch.tsx
**before selecting field:**
**after selecting field:**
**1. disable uploader if user doesn't choose collection**
**2. change warning message if user uploaded `is_primary_key` and `autoID` both true field**
=> Fix vector search style problem and update insert uploading validation check warning

client/src/http/Collection.ts, client/src/i18n/cn/collection.ts, client/src/i18n/en/collection.ts, client/src/pages/collections/Collections.tsx, server/generate-csv.ts, server/package.json, server/src/collections/collections.service.ts, server/yarn.lock
=> add created time in collection

client/src/components/customProgress/CustomLinearProgress.tsx, client/src/components/customProgress/Types.ts, client/src/http/Index.ts, client/src/i18n/cn/index.ts, client/src/i18n/en/index.ts, client/src/pages/overview/collectionCard/CollectionCard.tsx, client/src/pages/schema/IndexTypeElement.tsx, server/src/schema/dto.ts
=> add show index build progres

client/src/i18n/cn/search.ts, client/src/i18n/en/search.ts, client/src/pages/seach/Styles.ts, client/src/pages/seach/Types.ts, client/src/pages/seach/VectorSearch.tsx, client/src/utils/search.ts
=> Add dimension validation before search

server/src/collections/collections.controller.ts
=> Hide cache for now

client/src/pages/seach/VectorSearch.tsx, client/src/utils/search.ts
=> Fix not show id field in vector search

client/src/App.tsx, client/src/consts/Http.ts, client/src/context/Types.ts, client/src/context/WebSocket.tsx, client/src/http/Milvus.ts, client/src/pages/collections/Collections.tsx, client/src/pages/connect/Connect.tsx, client/src/utils/Validation.ts, server/generate-csv.ts, server/package.json, server/src/app.module.ts, server/src/collections/collections.controller.ts, server/src/collections/collections.module.ts, server/src/collections/collections.service.ts, server/src/crons/crons.controller.spec.ts, server/src/crons/crons.controller.ts, server/src/crons/crons.module.ts, server/src/crons/crons.service.spec.ts, server/src/crons/crons.service.ts, server/src/crons/dto.ts, server/src/events/events.gateway.ts, server/src/events/events.module.ts, server/src/utils/Const.ts, server/yarn.lock
Because of collections data may be big, so we still use ajax to fetch data.
Only when collection list includes index building or loading collection.
Only change collections page in this pr.
=> Use websocket to update index and loading status.

client/src/context/WebSocket.tsx, client/src/pages/overview/Overview.tsx, server/src/crons/crons.service.ts, server/src/milvus/milvus.service.ts
Also improve error message and ws
=> Add ws for overview page

server/package.json, server/src/milvus/milvus.controller.ts, server/src/milvus/milvus.service.ts, server/yarn.lock
=> Update sdk and add metric api

client/src/components/icons/Icons.tsx, client/src/components/icons/Types.ts, client/src/http/Collection.ts, client/src/i18n/cn/collection.ts, client/src/i18n/cn/dialog.ts, client/src/i18n/en/collection.ts, client/src/i18n/en/dialog.ts, client/src/pages/collections/Collections.tsx, client/src/pages/collections/CreateAlias.tsx, client/src/pages/collections/Types.ts, express/package.json, express/src/collections/collections.service.ts, express/src/collections/index.ts, express/yarn.lock
=> add collection alias and update sdk

client/src/components/advancedSearch/Condition.tsx, client/src/components/advancedSearch/Filter.tsx, client/src/components/advancedSearch/Types.ts, client/src/components/grid/Types.ts, client/src/http/BaseModel.ts, client/src/http/Collection.ts, client/src/i18n/cn/button.ts, client/src/i18n/cn/collection.ts, client/src/i18n/en/button.ts, client/src/i18n/en/collection.ts, client/src/pages/collections/Collection.tsx, client/src/pages/query/Query.tsx, client/src/pages/query/Styles.ts, client/src/pages/query/Types.ts, express/src/app.ts, express/src/collections/collections.service.ts, express/src/collections/index.ts, express/src/utils/index.ts
Main page:
Filter:
Main page with results:
Error page:
=> Add data query

client/src/http/Collection.ts, client/src/i18n/cn/collection.ts, client/src/i18n/en/collection.ts, client/src/pages/collections/Types.ts, client/src/pages/query/Query.tsx, express/src/collections/collections.controller.ts, express/src/collections/collections.service.ts
=> add delete entites in query tab

client/package.json, client/public/env-config.js, client/src/App.tsx, client/src/components/customDatePicker/CustomDatePicker.tsx, client/src/components/customDatePicker/Types.ts, client/src/components/icons/Icons.tsx, client/src/components/icons/Types.ts, client/src/hooks/TimeTravel.ts, client/src/i18n/cn/search.ts, client/src/i18n/en/search.ts, client/src/pages/query/Query.tsx, client/src/pages/query/Styles.ts, client/src/pages/query/Types.ts, client/src/plugins/search/Types.ts, client/src/plugins/search/VectorSearch.tsx, client/src/styles/theme.ts, client/src/utils/Format.ts, client/yarn.lock
=> Add time travel in vector search. Milvus is not support it in query yet.

client/package.json, client/src/components/icons/Icons.tsx, client/src/components/icons/Types.ts, client/src/i18n/cn/collection.ts, client/src/i18n/en/collection.ts, client/src/pages/query/Query.tsx, client/src/utils/Format.ts, client/yarn.lock
Disable if no result:
Enable:
csv file:
=> Add csv downloader to query

client/src/components/advancedSearch/Condition.tsx, client/src/components/advancedSearch/Types.ts, client/src/consts/Util.ts, client/src/http/Field.ts, client/src/pages/collections/Collections.tsx, client/src/pages/collections/Constants.ts, client/src/pages/collections/Types.ts, client/src/pages/schema/Create.tsx, client/src/pages/schema/Schema.tsx, client/src/pages/schema/Types.ts, client/src/plugins/search/Types.ts, client/src/types/SearchTypes.ts, client/src/utils/Form.ts, client/src/utils/search.ts, server/generate-csv.ts
=> support bool field

client/src/components/advancedSearch/Condition.tsx, client/src/components/advancedSearch/Types.ts, client/src/pages/query/Query.tsx, client/src/utils/search.ts
=> fix bool data display

client/src/pages/query/Query.tsx, express/src/collections/collections.controller.ts
=> fix query pagination and return all data from milvus response

.github/workflows/dev.yml, .github/workflows/release.yml
=> fix action node version

client/src/i18n/cn/insert.ts, client/src/i18n/en/insert.ts, client/src/pages/overview/collectionCard/CollectionCard.tsx
Because we use hash router instead of browser router, So we can't use Link component in material-ui. 
Need to use Link component in react-router-dom.
=> fix wrong link

client/src/plugins/system/config.json, express/src/middlewares/index.ts
=> fix 401 error when refresh page
